version: "3.8"
services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalogdb_volume:/data/db
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  discountdb:
    container_name: discountdb
    restart: always
    ports:
      - "5555:5432"
    volumes:
      - discountdb_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=discountdb
  identitydb:
    container_name: identitydb
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - identitydb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1234

  orderdb:
    container_name: orderdb
    restart: always
    ports:
      - "1444:1433"
    volumes:
      - orderdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1234
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQUrl:rabbitmq
      - IdentityServerURL:http://identityserver.api:5001
      - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
    ports:
      - "5011:80"
    depends_on:
      - catalogdb

  identityserver.api:
    container_name: identityserver.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=identitydb,1433; Database=IdentityDb; User Id=sa; Password=Password1234"
    ports:
      - "5001:80"
    depends_on:
      - identitydb

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL:http://identityserver.api:5001
      - RedisSettings:Port=6379
      - RedisSettings:Host=basketdb
    ports:
      - "5013:80"
    depends_on:
      - basketdb

  photostock.api:
    container_name: photostock.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL:http://identityserver.api:5001
    ports:
      - "5012:80"
    volumes:
      - type: bind
        source: C:\Users\akdem\Desktop\PhotoStock\photos
        target: /app/wwwroot/photos
